name: Node.js Package

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v6
        with:
          node-version: 24
          cache: pnpm
          registry-url: https://registry.npmjs.org/
      - run: |
          pnpm install --frozen-lockfile
          pnpm build
          pnpm publish --no-git-checks
        env:
          NODE_AUTH_TOKEN: ${{ secrets.npm_token }}